### ISSUE TITLE
display the audio track for the part of the video

### ISSUE THREAD

**Issue by danielcebrian** [collab-project/videojs-wavesurfer#3]
Hello, excellent plugin.

I would like to have an idea, on how to display the audio track for the part of the video that has been loaded into the player, because in your case you hide the video image, right? Is this possible?

Thank you,
Best regards,
Daniel

**Comment by thijstriemstra** [comment]
Thanks @danielcebrian. This plugin basically allows you to playback audio files using the video.js player controls. It then uses wavesurfer.js to create a visual representation of the loaded audio file. So it currently doesn't support video, it's only for audio. If I understand you correctly you basically want to load in a video file, hide the video stream itself, and render the audio signal of that video clip instead?

**Comment by danielcebrian** [comment]
thank you for the quick answer, I would like to have both things

**Comment by thijstriemstra** [comment]
I like the idea but since I'm not using that functionality in my own projects, it would take me a while to get to implementing something like that. Pull requests are always welcome and I'll try to give feedback where I can. Perhaps it might be something that can be implemented in wavesurfer.js so it can be used in this plugin. I believe there was some support added for `<video>` elements not long ago..

**Comment by thijstriemstra** [comment]
Well it turned out to be already working! :) Simply grab the latest wavesurfer.js release (1.0.16 at time of this writing) and try out the new video.html example I added just now. Let me know how it goes @danielcebrian, so I can release it after some testing.

**Comment by thijstriemstra** [comment]
Released as 0.9.3.
