### ISSUE TITLE
Using videojs-wavesurfer with React

### ISSUE THREAD

**Issue by TRomesh** [collab-project/videojs-wavesurfer#33]
## Description
Using videojs-wavesurfer with React
## Steps to reproduce
Im trying use videojs-wavesurfer and faced some issues. i installed the necessary packages **npm install videojs-wavesurfer** 
and add the some script tags **<link href="./lib/style.css" rel="stylesheet">
    <link href="../node_modules/video.js/dist/video-js.min.css" rel="stylesheet">
    <script src="lib/videojs.wavesurfer.js"></script>**
 to my index.html and imported 
**import videojs from "video.js";
import wavesurfer from "wavesurfer.js";** to my react component.

## Results
The component does not render but gives an error

### Error output
TypeError: The element or ID supplied is not valid. (videojs)
in line  21961 |   throw new TypeError('The element or ID supplied is not valid. (videojs)');

## Additional Information
Please include any additional information necessary here. Including the following:
#### videojs/wavesurfer
latest
#### browsers
chrome 58
#### OSes
ubuntu 14.04

**Comment by thijstriemstra** [comment]
@TRomesh I never used react but tried to create an example, see this branch: https://github.com/collab-project/videojs-wavesurfer/tree/react-example-33

Basically check out the branch, e.g.:

```
git clone https://github.com/collab-project/videojs-wavesurfer.git
cd videojs-wavesurfer
git checkout react-example-33
```
Change to the example directory and install the components:

```
cd examples/react-example
npm install
```
And start the development server:

```
npm start
```
This will launch a webserver and the example will be available on http://localhost:3000/

But as you will notice, when visiting the page it gives the following error message:

```
./node_modules/videojs-wavesurfer/dist/videojs.wavesurfer.js
Module not found: Can't resolve 'wavesurfer' in '/home/foo/projects/videojs-wavesurfer/examples/react-example/node_modules/videojs-wavesurfer/dist'
```

And I haven't figured out how to solve this. Also note that wavesurfer.js v2 beta or newer is required.

@mspae do you have idea how I can work around this issue and why wavesurfer can't be resolved? do I need react-wavesurfer?

**Comment by mspae** [comment]
@thijstriemstra @TRomesh TL;DR: The AMD module name and the npm package name are different and webpack/react-starter doesn't know how to handle this.

The AMD module name in the `wavesurfer.js` UMD package is called `wavesurfer` (because of https://github.com/katspaugh/wavesurfer.js/issues/831), the `videojs-wavesurfer` UMD header expects this AMD import and I assume the react scripts bundler just uses the first bundler it can make sense of.

There are two ways to solve this:

* Shim the module bundler so it uses common JS not AMD
* Alias `wavesurfer` to `wavesurfer.js`

Not sure how this can be achieved without running `npm run eject` and customising the webpack config. If you do that, then this might be of help: https://github.com/mspae/react-wavesurfer/issues/64#issuecomment-326730591

**Comment by thijstriemstra** [comment]
Thanks that's very helpful info!

**Comment by thijstriemstra** [comment]
Blocked by #29 and #32 (a.k.a. v2.0.0).

**Comment by thijstriemstra** [comment]
@TRomesh I've added an example in the upcoming v2.0.0 that was merged to master (and will be released soon). Can you checkout the git master branch and test if the react example is working for you?

**Comment by thijstriemstra** [comment]
> I've added an example in the upcoming v2.0.0 that was merged to master

2.0.0 was released just now.
